import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { getPlans, updatePlan, addPlan, syncPlanWithStripeById } from "@/lib/server/plans";

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session?.user?.email) {
      return NextResponse.json(
        { message: "Unauthorized" },
        { status: 401 }
      );
    }

    // Check if user is admin
    if (!(session as any).user?.isAdmin) {
      return NextResponse.json(
        { message: "Admin access required" },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { title, description, features, monthlyPrice, yearlyPrice, isActive, isPopular, stripePriceIds } = body;

    // Validate required fields
    if (!title || !description || !features || features.length === 0) {
      return NextResponse.json(
        { message: "Title, description, and at least one feature are required" },
        { status: 400 }
      );
    }

    // Create new plan
    console.log('Admin creating new plan:', { title, hasStripePriceIds: !!stripePriceIds });
    const newPlan = await addPlan({
      id: '', // Will be generated by database
      title,
      description,
      features,
      monthlyPrice: monthlyPrice || 0,
      yearlyPrice: yearlyPrice || 0,
      isActive: isActive !== undefined ? isActive : true,
      isPopular: isPopular || false,
      stripePriceIds,
    });

    // Sync with Stripe (creates/updates product and prices; stores IDs)
    try {
      await syncPlanWithStripeById(newPlan.id);
    } catch (e) {
      console.error('Stripe sync failed for new plan', newPlan.id, e);
      // We do not fail the request; admin can retry
    }

    return NextResponse.json(
      { 
        message: "Plan created successfully",
        plan: newPlan
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Plan creation error:", error);
    return NextResponse.json(
      { message: "Internal server error" },
      { status: 500 }
    );
  }
}

export async function PUT(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session?.user?.email) {
      return NextResponse.json(
        { message: "Unauthorized" },
        { status: 401 }
      );
    }

    // Check if user is admin
    if (!(session as any).user?.isAdmin) {
      return NextResponse.json(
        { message: "Admin access required" },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { id, title, description, features, monthlyPrice, yearlyPrice, isActive, isPopular, stripePriceIds } = body;

    // Update plan using the server function
    console.log('Admin updating plan:', { id, title, hasStripePriceIds: !!stripePriceIds, stripePriceIds });
    const updatedPlan = await updatePlan(id, {
      title,
      description,
      features,
      monthlyPrice,
      yearlyPrice,
      isActive,
      isPopular,
      stripePriceIds,
    });

    if (!updatedPlan) {
      return NextResponse.json(
        { message: "Plan not found" },
        { status: 404 }
      );
    }

    // If admin supplied explicit price IDs, preserve them and skip auto-sync overwrite
    const adminProvidedBothIds = !!(stripePriceIds && stripePriceIds.monthly && stripePriceIds.yearly);
    if (adminProvidedBothIds) {
      console.log('Admin provided explicit Stripe price IDs; skipping auto sync.');
    } else {
      // Sync with Stripe (creates/updates product and prices; stores IDs)
      try {
        await syncPlanWithStripeById(updatedPlan.id);
      } catch (e) {
        console.error('Stripe sync failed for plan', updatedPlan.id, e);
        // We do not fail the request; admin can retry
      }
    }

    return NextResponse.json(
      { 
        message: "Plan updated successfully",
        plan: updatedPlan
      },
      { status: 200 }
    );
  } catch (error) {
    console.error("Plan update error:", error);
    return NextResponse.json(
      { message: "Internal server error" },
      { status: 500 }
    );
  }
}
